apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-flask
  namespace: secure-zone
  labels:
    app: vulnerable-flask
spec:
  securityContext:
    fsGroup: 1000
  containers:
  - name: flask-app
    image: fazlulkarim105925/vulnerable-app1-k8s:latest
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
    ports:
    - containerPort: 8000
