apiVersion: v1
kind: Service
metadata:
  name: vulnerable-flask-service
  namespace: secure-zone
spec:
  type: NodePort
  selector:
    app: vulnerable-flask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
