apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: public-apps
  labels:
    app: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
      - name: app
        image: fazlulkarim105925/vulnerable-app-2-k8s:latest
        ports:
        - containerPort: 5000
