apiVersion: v1
kind: Service
metadata:
  name: redis-app-svc
  namespace: public-apps
spec:
  selector:
    app: redis-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  type: NodePort
